[package]
name = "axl_rules"
version = "0.1.0"
edition = "2024"

[dependencies]
axl_aria = { version = "0.1.0", path = "../axl_aria" }
axl_contrast = { version = "0.1.0", path = "../axl_contrast" }
axl_core = { version = "0.1.0", path = "../axl_core" }
axl_patterns = { version = "0.1.0", path = "../axl_patterns" }
