[package]
name = "axl_cli"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
axl_config = { version = "0.1.0", path = "../axl_config" }
axl_core = { version = "0.1.0", path = "../axl_core" }
axl_parser = { version = "0.1.0", path = "../axl_parser" }
axl_rules = { version = "0.1.0", path = "../axl_rules" }
clap.workspace = true
serde_json.workspace = true
